services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile-web
    network_mode: host
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  backend:
    build:
      context: ./
      dockerfile: Dockerfile-backend
    network_mode: host
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
