services:
  web:
    build:
      context: ./apps/web/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  # backend:
  #   build:
  #     context: ./apps/web/
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
