name: Lint Next.js Code

on:
  pull_request:
    paths:
      - "apps/web/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"

      - name: Install dependencies
        run: npm install

      - name: Run Next.js linter
        run: npm run -w web lint
